//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesCampanasPPG.BDCampana
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoAlcance
    {
        public int ID { get; set; }
        public string Alcance { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> Fecha_Creacion { get; set; }
        public Nullable<System.DateTime> Fecha_Modificacion { get; set; }
    }
}
