//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesCampanasPPG.BDCampana
{
    using System;
    using System.Collections.Generic;

    public partial class Usuario
    {
        public int ID { get; set; }
        public string PPGID { get; set; }
        public string Nombre { get; set; }
        public string Correo { get; set; }
        public Nullable<int> ID_RolCronograma { get; set; }
        public string Rol { get; set; }
        public string RolDescription { get; set; }
        public int Estatus { get; set; }
        public Nullable<System.DateTime> Fecha_Creacion { get; set; }
        public Nullable<System.DateTime> Fecha_Modificacion { get; set; }
        public RolCronograma RolCronograma = new RolCronograma();
        public string Mensaje { get; set; }
        public int OK { get; set; }
        //MENU
        public bool MenuUsuario { get; set; }
        public bool MenuCronograma { get; set; }
        public bool MenuGrafico { get; set; }
        public bool MenuConfiguracion { get; set; }
    }
}
